# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end


Blog.create(title: "My Cat's Secret Life as a Spy: The Furry Files", body: "Mr. Whiskers isn't just a lazy feline who sleeps 20 hours a day - or so I thought. After installing a pet camera, I've uncovered the truth: my cat is a secret agent. By day, he's sprawled on the couch, but by night, he's decoding messages in his litter box, speaking in code to the neighborhood strays, and practicing parkour across the kitchen counters. I've caught him wearing a tiny earpiece and meowing into what I can only assume is a high-tech collar. Who knew my furball was the James Bond of the animal kingdom? Move over, MI6 - the CIA (Cat Intelligence Agency) is in town.", user_id: 1)

Blog.create(title: "Confessions of a Serial Plant Killer: My Journey to Green Thumb Redemption", body: "
I've always wanted to be that person with a lush, jungle-like apartment, but instead, I've created a plant graveyard. My track record includes murdering countless succulents (how do you overwater a cactus?), turning herb gardens into dried spice collections, and somehow managing to kill an artificial plant. Yes, you read that right. But I'm determined to change. Follow my misadventures as I attempt to keep a plant alive for more than a week, armed with nothing but determination, a watering can, and a PhD in Googling 'why are my plant's leaves turning brown?' Will I finally achieve planthood redemption, or will I be forever banned from the garden center? Stay tuned for the chlorophyll-filled drama!", user_id: 1)

Blog.create(title: "The Great Sock Conspiracy: Where Do They Really Go in the Dryer?", body: "It's time to unravel the greatest mystery of modern domesticity: the case of the vanishing socks. We've all experienced it - you put in a perfect pair, but only one emerges from the dryer's depths. Where do they go? I've developed several theories: 1) There's a portal to a parallel universe inside my dryer where single socks live in harmony, 2) Socks are actually sentient and are escaping their cotton slavery one at a time, or 3) My dryer is actually a hungry sock monster with a very particular palate. Join me as I don my detective hat, arm myself with a flashlight, and venture into the lint-filled unknown to crack this case wide open. The truth is out there, probably hiding behind the laundry detergent.", user_id: 1)

Blog.create(title: "Yoga Fails: Downward Dog Turned Upside-Down Disaster", body: "Namaste? More like Nama-stay away from yoga! My journey into the world of yoga has been less about finding inner peace and more about finding new ways to embarrass myself. Picture this: me, attempting a downward dog, only to have my mat slip, sending me sliding across the floor like a human mop. Or the time I misheard 'child's pose' as 'child's throws' and started tossing imaginary objects around the room. Let's not forget the incident with the yoga ball that sent me bouncing into the next room. If you think yoga is all about zen and flexibility, allow me to bend your perspective with my tales of twisted limbs and bruised egos. Warning: reading this blog may cause spontaneous laughter and a sudden appreciation for your couch.", user_id: 1)

Blog.create(title: "I Tried to Marie Kondo My Life and Now I Live in an Empty Box", body: "Inspired by the tidying guru herself, I decided to embrace minimalism and only keep items that 'spark joy.' Little did I know, I'd end up living in a cardboard box with a spork and a half-empty bottle of shampoo. Turns out, not much in my life sparked joy besides my extensive collection of takeout menus (which, ironically, no longer spark joy since I can't afford takeout). Follow my journey as I navigate life with one shirt, no furniture, and a newfound appreciation for the joy-sparking qualities of basic necessities. Who needs a bed when you can sleep on a pile of joyful memories? Marie Kondo, if you're reading this, please send help - and maybe a chair.", user_id: 1)
